name: is_dart_empty_or_not
description: A Dart package that provides extensions for checking empty or zero values
version: 0.3.0
homepage: https://github.com/Arenukvern/is_dart_empty_or_not
environment:
  sdk: ">=3.10.0 <4.0.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.29.0
  xsoulspace_lints: ^0.1.2
